### ISSUE TITLE
[backend] Requests to add badges with an empty identifier are not blocked

### ISSUE THREAD

**Issue by LaniJW** [kiangribi/m242_lb02#18]

**Comment by kiangribi** [comment]
Do you think we should add a regex validator so that the badge ids have to be in the format "ff:ff:ff:ff"?

**Comment by LaniJW** [comment]
That doesn't sound like a bad idea. I've been meaning to ask you that. But also how would you handle badges only using 6 characters instead of 8 and maybe some badges have longer IDs. I think for the sake of simplicity we should just check with this regex: `[A-Za-z0-9:]+`.

**Comment by kiangribi** [comment]
What do you think about `([a-f0-9]{2}\:)+[a-f0-9]{2}` to be a bit more restrictive?

**Comment by LaniJW** [comment]
Yes, that sounds reasonable.

**Comment by kiangribi** [comment]
Fixed by d1ed5ff3a5bf3c9e46843c020dcc38ffe785285b
