### ISSUE TITLE
[frontend] Remove unneccessary invalid signs

### ISSUE THREAD

**Issue by kiangribi** [kiangribi/m242_lb02#25]
Not quite sure if this is needed
![2020-05-02-170625_932x400_scrot](https://user-images.githubusercontent.com/31879715/80867935-5f987a00-8c97-11ea-9bcf-a5fc6b571262.png)

**Comment by LaniJW** [comment]
What? the crosses in the fields?

**Comment by kiangribi** [comment]
Yes, I mean do we need them if the form was not submitted before?

**Comment by LaniJW** [comment]
These aren't invalid signs. They allow you to clear the contents of the input
