### ISSUE TITLE
[frontend] Update row dropdown on refresh

### ISSUE THREAD

**Issue by kiangribi** [kiangribi/m242_lb02#30]
![2020-05-04-123753_614x139_scrot](https://user-images.githubusercontent.com/31879715/80957757-19145e00-8e04-11ea-8fb7-55d02cfcfc1e.png)

**Comment by LaniJW** [comment]
I can't tell what's wrong here.

**Comment by kiangribi** [comment]
Nevermind that is my bad. I was not aware of the 5 10 15 step.
