### ISSUE TITLE
[frontend] Add proper titles to pages

### ISSUE THREAD

**Issue by kiangribi** [kiangribi/m242_lb02#32]
![2020-05-04-130513_300x87_scrot](https://user-images.githubusercontent.com/31879715/80959829-e66c6480-8e07-11ea-8619-b62e37fc5409.png)

**Comment by LaniJW** [comment]
Firefox issue. Works in chrome
![image](https://user-images.githubusercontent.com/39264510/80960270-dbfe9a80-8e08-11ea-977f-a07affcff149.png)

**Comment by kiangribi** [comment]
Is there a <title> tag?

**Comment by LaniJW** [comment]
There is. I know how to fix it and I can take a look tomorrow if you'd like

**Comment by LaniJW** [comment]
There is. I can try and fix this tomorrow maybe

**Comment by kiangribi** [comment]
Not sure if this is needed tho, I will present on the tablet where chrom is used

**Comment by LaniJW** [comment]
Seems to be a Firefox caching bug. Won't fix.
